//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bambo.Models.Databsae
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.Tbl_Admin = new HashSet<Tbl_Admin>();
        }
    
        public int AddersID { get; set; }
        public Nullable<int> CustomerFk { get; set; }
        public string ReciptionName { get; set; }
        public string FullAddress { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public Nullable<int> PostalCode { get; set; }
        public string PhoneNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Admin> Tbl_Admin { get; set; }
    }
}
