//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bambo.Models.Databsae
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string PasswordHashed { get; set; }
        public Nullable<int> RoleFK { get; set; }
        public Nullable<int> AddressFK { get; set; }
        public Nullable<int> WhishListFk { get; set; }
        public Nullable<int> ReviewFK { get; set; }
        public byte[] Image { get; set; }
        public string VerficationCode { get; set; }
    }
}
