//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bambo.Models.Databsae
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int DiscountId { get; set; }
        public int DiscountCode { get; set; }
        public string DidcountType { get; set; }
        public decimal DiscountValue { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> OrderditailsFk { get; set; }
    
        public virtual OderDitals OderDitals { get; set; }
    }
}
