//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bambo.Models.Databsae
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public decimal Price { get; set; }
        public string ProductName { get; set; }
        public int StockQuantity { get; set; }
        public byte[] Image { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public Nullable<int> WhishListID { get; set; }
        public string ProductCode { get; set; }
        public Nullable<double> ProductRate { get; set; }
        public string Discription { get; set; }
        public bool Granantee { get; set; }
        public int HighlightsID { get; set; }
        public Nullable<bool> IsAvaible { get; set; }
        public byte[] Image1 { get; set; }
        public byte[] Image2 { get; set; }
        public byte[] Image3 { get; set; }
        public byte[] Image4 { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<System.DateTime> ExpireAt { get; set; }
    
        public virtual Brand Brand { get; set; }
    }
}
