//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bambo.Models.Databsae
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productwhish
    {
        public int ProductId { get; set; }
        public int Wish { get; set; }
    
        public virtual WishList WishList { get; set; }
    }
}
