//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bambo.Models.Databsae
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewID { get; set; }
        public Nullable<int> ProductFK { get; set; }
        public Nullable<int> CustomerFk { get; set; }
        public int Rate { get; set; }
        public string Commernt { get; set; }
        public int ReviewRate { get; set; }
    }
}
